# PyRadiomics params
setting:
  binWidth: 25
  resampledPixelSpacing: [1, 1]
  interpolator: 'sitkBSpline'
  normalize: true
  normalizeScale: 100
  removeOutliers: [3, 3]
  correctMask: true

imageType:
  Original: {}
  Wavelet: {}
  LoG:
    sigma: [1.0, 3.0, 5.0]

featureClass:
  shape:
    - VoxelVolume
    - SurfaceArea
  firstorder:
    - Mean
    - Variance
    - Skewness
  glcm:
    - Contrast
    - Correlation
    - Dissimilarity
  glrlm:
    - ShortRunEmphasis
    - LongRunEmphasis
  glszm:
    - SmallAreaEmphasis
    - LargeAreaEmphasis
  gldm:
    - DependenceEntropy
  ngtdm:
    - Coarseness

